FROM node:23-alpine3.21 AS builder

WORKDIR /client

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

ARG API_PREFIX
ARG API_URL_DJANGO

ENV VITE_API_URL_DJANGO=${API_URL_DJANGO}${API_PREFIX}


RUN npm run build

FROM nginx:stable-alpine

RUN apk --no-cache add gettext

COPY --link nginx.conf /etc/nginx/conf.d/default.conf

COPY --link --from=builder /client/dist /usr/share/nginx/html


EXPOSE 8080



