FROM node:23-alpine3.21 AS builder

WORKDIR /client

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM nginx:stable-alpine

RUN apk --no-cache add gettext

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /client/dist /usr/share/nginx/html

CMD ["sh", "-c", "envsubst '${DJANGO_PORT}' < /etc/nginx/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]

EXPOSE 8080